In [1]:
#Installing the libraries for data cleaning
import pandas as pd
import numpy as np
import regex as re

In [2]:
#Loading the data
data = pd.read_csv('messy_customer_orders.csv')
data

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.57,154.28,Shipped,PayPal,TRUE
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,NaN,NaN,Shipped,Cash,True
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,NaN,NaN,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.93,385.86,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.80,pending,Bank Transfer,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,ORD-011285,CUST-1678,14/11/2022,USA,ELECTRONICS,Resistance Bands,1,97.0,96.77,delivered,Cash,no
50996,ORD-044733,CUST-5264,07-16-2022,U.S.A,books,Backpack,4,274.66,1098.64,cancelled,Bank Transfer,False
50997,ORD-038159,CUST-0710,2023-06-04,United Kingdom,books,USB Hub,2,25.21,50.42,Delivered,Cash,FALSE
50998,ORD-000861,CUST-4352,14/02/2024,DE,electronics,Python Programming Book,1,176.64,176.64,Cancelled,Cash,No
50999,ORD-015796,CUST-7019,2023-08-04,canada,BOOKS,Desk Lamp,8,£148.71,1189.68,cancelled,Credit Card,1

In [3]:
#Making an copy of the data for disaster management
data_copy = data.copy()

In [4]:
#Tracking the number of null values are there in each columns
data_copy.isnull().sum()

order_id             0
customer_id       2033
order_date           0
country           2540
category          3052
product              0
quantity             0
unit_price        2033
total_amount      1528
status               0
payment_method       0
is_returned          0
dtype: int64

In [5]:
#Tracking for the duplicate values
duplicate_values = data_copy.duplicated().sum()
print("Count of Duplicated Values are : ",duplicate_values)
data_copy[data_copy.duplicated(keep=False)].sort_values('order_id').head(10)

Count of Duplicated Values are :  1000

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
17684,ORD-000086,CUST-6333,25 Nov 2023,United States,Sports,Notebook Set,9,248.98,2240.82,pending,Bank Transfer,TRUE
18714,ORD-000086,CUST-6333,25 Nov 2023,United States,Sports,Notebook Set,9,248.98,2240.82,pending,Bank Transfer,TRUE
1064,ORD-000093,CUST-3114,2024-01-11,Australia,Sports,Travel Mug,7,$246.96,1728.72,Cancelled,Cash,False
18156,ORD-000093,CUST-3114,2024-01-11,Australia,Sports,Travel Mug,7,$246.96,1728.72,Cancelled,Cash,False
21365,ORD-000109,CUST-0585,2022-12-25,USA,Sports,Python Programming Book,3,244.67,734.01,Delivered,PayPal,TRUE
11092,ORD-000109,CUST-0585,2022-12-25,USA,Sports,Python Programming Book,3,244.67,734.01,Delivered,PayPal,TRUE
41112,ORD-000122,CUST-5638,18/06/2023,germany,ELECTRONICS,Laptop Stand,9,147.14,1324.26,DELIVERED,PayPal,yes
17112,ORD-000122,CUST-5638,18/06/2023,germany,ELECTRONICS,Laptop Stand,9,147.14,1324.26,DELIVERED,PayPal,yes
28614,ORD-000392,CUST-0765,06-11-2022,canada,Books,USB Hub,4,111.76,447.04,Delivered,Credit Card,No
38436,ORD-000392,CUST-0765,06-11-2022,canada,Books,USB Hub,4,111.76,447.04,Delivered,Credit Card,No

In [6]:
#Droping the Duplicated values
data_copy = data_copy.drop_duplicates()

In [7]:
#Now checking duplicates values and the shape of the dataset after removing the duplicate values
data_shape = data_copy.shape
print("The Shape of the data after removing duplicates : ",data_shape)
data_copy[data_copy.duplicated(keep=False)].sort_values('order_id').head(10)

The Shape of the data after removing duplicates :  (50000, 12)

Empty DataFrame
Columns: [order_id, customer_id, order_date, country, category, product, quantity, unit_price, total_amount, status, payment_method, is_returned]
Index: []

In [8]:
data_copy

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.57,154.28,Shipped,PayPal,TRUE
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,NaN,NaN,Shipped,Cash,True
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,NaN,NaN,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.93,385.86,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.80,pending,Bank Transfer,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,ORD-011285,CUST-1678,14/11/2022,USA,ELECTRONICS,Resistance Bands,1,97.0,96.77,delivered,Cash,no
50996,ORD-044733,CUST-5264,07-16-2022,U.S.A,books,Backpack,4,274.66,1098.64,cancelled,Bank Transfer,False
50997,ORD-038159,CUST-0710,2023-06-04,United Kingdom,books,USB Hub,2,25.21,50.42,Delivered,Cash,FALSE
50998,ORD-000861,CUST-4352,14/02/2024,DE,electronics,Python Programming Book,1,176.64,176.64,Cancelled,Cash,No
50999,ORD-015796,CUST-7019,2023-08-04,canada,BOOKS,Desk Lamp,8,£148.71,1189.68,cancelled,Credit Card,1

In [9]:
#Now replacing the null values of total amount using median method
data_copy['total_amount'] = data_copy['total_amount'].fillna(data_copy['total_amount'].median())
data_copy

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.57,154.280,Shipped,PayPal,TRUE
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,NaN,690.105,Shipped,Cash,True
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,NaN,690.105,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.93,385.860,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.800,pending,Bank Transfer,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,ORD-011285,CUST-1678,14/11/2022,USA,ELECTRONICS,Resistance Bands,1,97.0,96.770,delivered,Cash,no
50996,ORD-044733,CUST-5264,07-16-2022,U.S.A,books,Backpack,4,274.66,1098.640,cancelled,Bank Transfer,False
50997,ORD-038159,CUST-0710,2023-06-04,United Kingdom,books,USB Hub,2,25.21,50.420,Delivered,Cash,FALSE
50998,ORD-000861,CUST-4352,14/02/2024,DE,electronics,Python Programming Book,1,176.64,176.640,Cancelled,Cash,No
50999,ORD-015796,CUST-7019,2023-08-04,canada,BOOKS,Desk Lamp,8,£148.71,1189.680,cancelled,Credit Card,1

In [10]:
for i in range(0,15):
  print(data_copy['total_amount'][i])

154.28
690.105
690.105
385.86
446.8
690.105
453.67
834.56
519.22
1920.61
690.105
1213.34
191.45
1991.29
10360.08

In [11]:
#let go for replacing the unit price null values

#firstly convert the object data type to string
data_copy['unit_price'] = data_copy['unit_price'].astype(str)

#secondly remove the special characters from the string
data_copy['unit_price'] = data_copy['unit_price'].str.replace(r'[^0-9.]','',regex=True)

#now convert the string column to float64
data_copy['unit_price'] = pd.to_numeric(data_copy['unit_price'],errors='coerce').astype('float64')

#finally replace the null values
data_copy['unit_price'] = data_copy['unit_price'].fillna(data_copy['unit_price'].median())
data_copy

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.570,154.280,Shipped,PayPal,TRUE
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,168.975,690.105,Shipped,Cash,True
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,168.975,690.105,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.930,385.860,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.700,446.800,pending,Bank Transfer,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,ORD-011285,CUST-1678,14/11/2022,USA,ELECTRONICS,Resistance Bands,1,97.000,96.770,delivered,Cash,no
50996,ORD-044733,CUST-5264,07-16-2022,U.S.A,books,Backpack,4,274.660,1098.640,cancelled,Bank Transfer,False
50997,ORD-038159,CUST-0710,2023-06-04,United Kingdom,books,USB Hub,2,25.210,50.420,Delivered,Cash,FALSE
50998,ORD-000861,CUST-4352,14/02/2024,DE,electronics,Python Programming Book,1,176.640,176.640,Cancelled,Cash,No
50999,ORD-015796,CUST-7019,2023-08-04,canada,BOOKS,Desk Lamp,8,148.710,1189.680,cancelled,Credit Card,1

In [12]:
data_copy.isnull().sum()

order_id             0
customer_id       2000
order_date           0
country           2500
category          3000
product              0
quantity             0
unit_price           0
total_amount         0
status               0
payment_method       0
is_returned          0
dtype: int64

In [13]:
#Now filling the remaining categorical columns
cate_col = ['customer_id','country','category']
data_copy[cate_col]  = data_copy[cate_col].fillna('unknown')
data_copy

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.570,154.280,Shipped,PayPal,TRUE
1,ORD-006584,unknown,10-12-2023,unknown,unknown,Backpack,-2,168.975,690.105,Shipped,Cash,True
2,ORD-013539,unknown,26/07/2023,unknown,unknown,Travel Mug,9,168.975,690.105,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.930,385.860,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.700,446.800,pending,Bank Transfer,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,ORD-011285,CUST-1678,14/11/2022,USA,ELECTRONICS,Resistance Bands,1,97.000,96.770,delivered,Cash,no
50996,ORD-044733,CUST-5264,07-16-2022,U.S.A,books,Backpack,4,274.660,1098.640,cancelled,Bank Transfer,False
50997,ORD-038159,CUST-0710,2023-06-04,United Kingdom,books,USB Hub,2,25.210,50.420,Delivered,Cash,FALSE
50998,ORD-000861,CUST-4352,14/02/2024,DE,electronics,Python Programming Book,1,176.640,176.640,Cancelled,Cash,No
50999,ORD-015796,CUST-7019,2023-08-04,canada,BOOKS,Desk Lamp,8,148.710,1189.680,cancelled,Credit Card,1

In [14]:
#now checking the null values
data_copy.isnull().sum()

order_id          0
customer_id       0
order_date        0
country           0
category          0
product           0
quantity          0
unit_price        0
total_amount      0
status            0
payment_method    0
is_returned       0
dtype: int64

In [15]:
data_copy.dtypes

order_id           object
customer_id        object
order_date         object
country            object
category           object
product            object
quantity            int64
unit_price        float64
total_amount      float64
status             object
payment_method     object
is_returned        object
dtype: object

In [16]:
# want to download the updated dataset
data_copy.to_csv("Updated customer orders data")